---
icinga2_api_username: root
icinga2_api_password: apipassword
icinga2_api_port: 5665

icinga2_enable_agent_snmp: yes

icinga2_snmpd_agentaddress: "udp:{{ ansible_default_ipv4.address }}:161"
icinga2_snmpd_rocommunity_addresses:
  - 127.0.0.1/32
