---
icinga2_graphite_user: root
icinga2_graphite_group: icingaweb2

icinga2_graphite_version: v1.1.0

icinga2_graphite_prerequsites:
  - cairo
  - git

icinga2_icingaweb_install_path: /usr/share/icingaweb2
icinga2_icingaweb_conf_dir: /etc/icingaweb2

icinga2_graphite_download_url: https://github.com/icinga/icingaweb2-module-graphite

icinga2_graphite_install_dir: /opt/graphite
icinga2_graphite_conf_dir: "{{ icinga2_graphite_install_dir }}/conf"

icinga2_graphite_port: 8070

icinga2_graphite_python_packages:
  - python3
  - python3-pip

icinga2_graphite_python_modules:
  - carbon
  - whisper
  - graphite-web
  - service_identity

icinga2_graphite_migration_script_download_url: https://raw.githubusercontent.com/graphite-project/graphite-web/master/webapp/manage.py

icinga2_graphite_default_storage_schemas: 60s:1d,5m:30d,1h:3y
