---
- name: Gather facts for localhost
  hosts: localhost
  gather_facts: false
  become: no
  tasks:
    - name: Find icinga2 plugins
      find:
        paths: "{{ playbook_dir }}/roles"
        recurse: no
        file_type: directory
        patterns: "plugin_*"
      delegate_to: localhost
      register: find_plugins
      when: >
        icinga2_force_plugins is not defined and
        icinga2_force_plugins|length == 0
    - set_fact:
        icinga2_plugins: "{{ icinga2_plugins | default([]) + [ item.path | basename ] }}"
      loop: "{{ find_plugins.files }}"
      when: >
        icinga2_force_plugins is not defined and
        icinga2_force_plugins|length == 0
    - set_fact:
        icinga2_plugins: "{{ icinga2_force_plugins }}"
      when: >
        icinga2_force_plugins is defined and
        icinga2_force_plugins|length > 0
    - name: Available icinga2 plugins
      debug:
        var: icinga2_plugins

- name: Gather facts for all hosts and set facts for autodetection.
  hosts:
    - clients
    - master
  serial: '{{ icinga2_serial|default("0") }}'
  gather_facts: True
  tasks:
    - name: Set default for enable_plugins
      set_fact:
        enable_plugins: "{{ [] }}"
    - name: Gather extended facts.
      deltabg.extended_facts.extended_facts:
    - name: Include role task set_facts
      include_role:
        name: "{{ item }}"
        tasks_from: "set_facts"
      loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
