---

- name: Install and configure plugins.
  hosts: clients
  gather_facts: no # Facts gathering has been already done in gather-facts.yml playbook.
  serial: "{{ playbook_serial|default(0) }}"
  tasks:
    - block:
        - name: Activated plugins for client 
          debug:
            var: enable_plugins
        - name: Include role task main
          include_role:
            name: "{{ plugin_name }}"
            tasks_from: "main"
          loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
          loop_control:
            loop_var: plugin_name
          when: plugin_name in enable_plugins
      when: >
        hostvars[groups['master'][0]]['icinga2_configured'] and
        icinga2_installed

- name: Configure the master services and commands.
  hosts: master
  gather_facts: no # Facts gathering has been already done in gather-facts.yml playbook.
  serial: "{{ playbook_serial|default(0) }}"
  handlers:
    - name: restart icinga2
      service:
        name: icinga2
        state: restarted
  tasks:
    - block:
        - name: Include role task master services
          include_role:
            name: "{{ item }}"
            tasks_from: "services"
          loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
        - name: Include role task master commands
          include_role:
            name: "{{ item }}"
            tasks_from: "commands"
          loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
      when: >
        hostvars[groups['master'][0]]['icinga2_configured'] and
        icinga2_installed

- name: Configure the clients commands.
  hosts: clients
  gather_facts: no # Facts gathering has been already done in gather-facts.yml playbook.
  serial: "{{ playbook_serial|default(0) }}"
  handlers:
    - name: restart icinga2
      service:
        name: icinga2
        state: restarted
  tasks:
    - block:
        # Needed in some cases where conf.d is not included on some clients. 
        - name: Ensure conf.d is included in main Icinga2 config.
          lineinfile:
            line: 'include_recursive "conf.d"'
            dest: "{{ icinga2_config_dir }}/icinga2.conf"
          notify: restart icinga2
        - name: Include role task client commands
          include_role:
            name: "{{ plugin_name }}"
            tasks_from: "commands"
          loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
          loop_control:
            loop_var: plugin_name
          when: plugin_name in enable_plugins
        - name: Include role task client vars
          include_role:
            name: "{{ plugin_name }}"
            tasks_from: "vars"
          loop: "{{ hostvars['localhost']['icinga2_plugins'] }}"
          loop_control:
            loop_var: plugin_name
          when: plugin_name in enable_plugins
      when: >
        hostvars[groups['master'][0]]['icinga2_configured'] and
        icinga2_installed
