---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Install required packages.
  package:
    name: "{{ icinga2_required_packages }}"
    state: present

- name: Download rabbitmq monitoring plugins.
  get_url:
    url: "{{ item }}"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/"
    mode: 0755
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
  loop: "{{ icinga2_rabbitmq_download_urls }}"
