---
- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    (icinga2_plugin_autodetect) or
    force_enable_plugin_rabbitmq
  # Enable plugin if machine is hardware and not virtual: ansible_virtualization_role == "host"
