---
- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    ((ansible_virtualization_role is defined and
    ansible_virtualization_role == "host") and
    (ansible_facts.ipmi is defined and
    ansible_facts.ipmi) and
    ansible_system == "Linux" and
    icinga2_plugin_autodetect) or 
    force_enable_plugin_ipmi
  # Enable plugin if machine is hardware and not virtual: ansible_virtualization_role == "host"
