---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if net_interfaces plugin has been already installed.
  stat:
    path: "{{ icinga2_nagios_plugins_install_dir }}/check_net_interfaces"
  register: icinga2_net_interfaces_chk

- name: Download the net_interfaces plugin source.
  get_url:
    url: "{{ icinga2_net_interfaces_download_url }}"
    dest: /tmp/
  when: not icinga2_net_interfaces_chk.stat.exists

- name: Unarchive net_interfaces plugin source.
  unarchive:
    src: "/tmp/ethMon-{{ icinga2_net_interfaces_version }}.tar.gz"
    remote_src: yes
    dest: /tmp/
  when: not icinga2_net_interfaces_chk.stat.exists

- name: Copy net_interfaces plugin to final destination.
  copy:
    src: "/tmp/ethMon-{{ icinga2_net_interfaces_version }}/ethMon"
    remote_src: yes
    dest: "{{ icinga2_nagios_plugins_install_dir }}/check_net_interfaces"
    mode: 0755
  when: not icinga2_net_interfaces_chk.stat.exists
