---

- name: Install centos-release-scl repository.
  package:
    name: centos-release-scl
    state: present
  when: >
    ansible_os_family == "RedHat" and
    ansible_distribution_major_version == "7"
