---
# Icinga2 config directory.
icinga2_config_dir: /etc/icinga2

# Force enable plugin
force_enable_plugin_ipmi: no

# Icinga2 master zone name
icinga2_zone_master_endpoint_name: "master"

icinga2_check_ipmi_sensor_download_url: "https://raw.githubusercontent.com/DeltaBG/icinga2-additional-plugins/main/check_ipmi_sensor"

# Default thresholds. They can be overwritten in group vars and host vars.
icinga2_plugin_ipmi_autoconfig: no # Automatically creates an IPMI user account
icinga2_plugin_ipmi_user_id: 10
icinga2_plugin_ipmi_username: "icinga2"
icinga2_plugin_ipmi_password: "Y0UrR4nD0mPaSS"
icinga2_plugin_ipmi_exclude_sensor_id: "1143,4091" # Comma-separated ID's. 1143 and 4091 is 'Chassis Intrusion'.
