---
- set_fact:
    have_bonding: yes
  loop: "{{ ansible_interfaces }}"
  loop_control:
    loop_var: interface
  when: hostvars[inventory_hostname]['ansible_%s' | format(interface) | regex_replace('-', '_')]['type'] == 'bonding'

- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    ((have_bonding is defined and
    have_bonding) and
    (ansible_system == "Linux" and
    icinga2_plugin_autodetect)) or
    force_enable_plugin_bonding
