---
icinga2_user: icinga
icinga2_group: icinga
icinga2_config_dir: /etc/icinga2
icinga2_zone_master_endpoint_name: "master"
icinga2_enable_flapping: no
icinga2_client_host: "{{ ansible_default_ipv4.address }}"
