---
# This command will exit non-zero when the root password was set previously
- name: Check if root password is unset.
  shell: >
    mysql -u root
    -p'{{ mysql_root_password }}'
    -h localhost
    -S {{ mysql_socket }}
    -e "quit"
  changed_when: false
  ignore_errors: true
  register: root_pwd_check

- name: Set MySQL root password for the first time (root@localhost).
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost
    login_unix_socket: "{{ mysql_socket }}"
    state: present
  when: root_pwd_check.rc != 0

- name: Set MySQL root password for 127.0.0.1, ::1, FQDN.
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    host: "{{ item }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    state: present
  with_items:
    - ::1
    - 127.0.0.1
    - "{{ ansible_fqdn }}"
  when: root_pwd_check.rc == 0

- name: Remove the test database.
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    state: absent

- name: Remove anonymous users.
  mysql_user:
    name: ''
    host_all: true
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
    state: absent
  no_log: true

- name: Configure mysql_database_host
  lineinfile:
    line: "bind-address={{ mysql_database_host }}"
    dest: /etc/my.cnf.d/mysql-server.cnf
