---
- name: Install MySQL server.
  package:
    name: "{{ __mysql_packages }}"
    state: present

- name: Enable and start MySQL server.
  service:
    name: "{{ __mysql_service_name }}"
    enabled: yes
    state: started
