---
- name: Set root MySQL password in /root/.my.cnf
  copy:
    dest: /root/.my.cnf
    mode: 0640
    content: |
      [client]
      user="root"
      password="{{ mysql_root_password }}"
  when: mysql_enable_root_my_cnf
