---
- name: Install Icinga2 packages.
  package:
    name: "{{ icinga2_package_names }}"
    state: present

- name: Enable and start Icinga2 service.
  service:
    name: icinga2
    enabled: yes
    state: started
