---
- name: Install Icinga2 packages.
  package:
    name: "{{ icinga2_package_name }}"
    state: present

- name: Enable and start Icinga2 service.
  service:
    name: "{{ icinga2_package_name }}"
    enabled: yes
    state: started
