---
- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    ((ansible_devices.keys()|list is defined and
    ansible_devices.keys()|list|length>0) and
    icinga2_plugin_autodetect) or
    force_enable_plugin_iostat
