---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Get check_raid plugin
  get_url:
    url: "{{ icinga2_check_raid_download_url }}"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/"
    mode: 0755

- block:
  - name: Get storcli64 binary
    get_url:
      url: "{{ icinga2_storcli64_binary_download_url }}"
      dest: "/usr/local/bin/"
      mode: 0755
  when: >
    ansible_facts.raid.megaraid is defined and
    ansible_facts.raid.megaraid|length>0

- name: Configure sudoers privileges.
  template:
    src: sudoers.j2
    dest: "/etc/sudoers.d/icinga2_plugin_raid"
    owner: "root"
    group: "root"
    mode: 0600
    validate: /usr/sbin/visudo -cf %s
