---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if check_raid plugin has been already installed.
  stat:
    path: "{{ icinga2_nagios_plugins_install_dir }}/check_raid/check_raid.sh"
  register: icinga2_check_raid_chk

- name: Install make package.
  package:
    name: make
    state: present
  when: not icinga2_check_raid_chk.stat.exists

- name: Install cpanm package.
  package:
    name: "{{ perl_cpanm_package }}"
    state: present
  when: not icinga2_check_raid_chk.stat.exists

- name: Download check_raid plugin.
  get_url:
    url: "{{ icinga2_check_raid_download_url }}"
    dest: "/tmp/"
  when: not icinga2_check_raid_chk.stat.exists

- name: Install check_raid perl modules.
  cpanm:
    name: "{{ item }}"
  loop:
    - Module::Install
    - Class::Accessor
    - Monitoring::Plugin
    - Module::Pluggable
  when: not icinga2_check_raid_chk.stat.exists

- name: Install check_raid Module::Pluggable perl module.
  cpanm:
    name: Module::Pluggable
    version: 5.2
  when: not icinga2_check_raid_chk.stat.exists

- name: Unpack check_raid plugin archive.
  unarchive:
    src: "/tmp/nagios-plugin-check_raid-{{ icinga2_check_raid_version }}.tar.gz"
    dest: /tmp/
    remote_src: yes
    mode: 0755
  when: not icinga2_check_raid_chk.stat.exists

- name: Copy unarchived check_raid dir to final destination.
  copy:
    src: "/tmp/nagios-plugin-check_raid-{{ icinga2_check_raid_version }}/"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/check_raid"
    remote_src: yes
    mode: 0755
  when: not icinga2_check_raid_chk.stat.exists
