---
- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    ((ansible_virtualization_role is defined and
    ansible_virtualization_role == "host") and
    (ansible_facts.raid is defined and 
    ansible_facts.raid|length>0) and
    icinga2_plugin_autodetect) or
    force_enable_plugin_raid
  # Enable plugin if machine is hardware and not virtual: ansible_virtualization_role == "host"
