---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if check_rbl plugin has been already installed
  stat:
    path: "{{ icinga2_nagios_plugins_install_dir }}/check_rbl"
  register: icinga2_check_rbl_chk

- name: Download check_rbl plugin
  get_url:
    url: "{{ icinga2_check_rbl_download_url }}"
    dest: "/tmp/"
  when: not icinga2_check_rbl_chk.stat.exists

- name: Unarchive check_rbl archive
  unarchive:
    src: "/tmp/check_rbl-{{ icinga2_check_rbl_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    mode: 0755
  when: not icinga2_check_rbl_chk.stat.exists

- name: Install make package.
  package:
    name: make
    state: present
  when: not icinga2_check_rbl_chk.stat.exists

- name: Install cpanm package.
  package:
    name: "{{ perl_cpanm_package }}"
    state: present
  when: not icinga2_check_rbl_chk.stat.exists

- name: Install perl modules
  cpanm:
    name: "{{ item }}"
  loop:
    - Module::Install
    - Net::IP
    - Net::DNS
    - Data::Validate::Domain
    - Data::Validate::IP
    - Readonly
    - Monitoring::Plugin
  when: not icinga2_check_rbl_chk.stat.exists

- name: Run perl Makefile.PL for check_rbl # noqa 305
  shell: "perl Makefile.PL"
  args:
    chdir: "/tmp/check_rbl-{{ icinga2_check_rbl_version }}"
  when: not icinga2_check_rbl_chk.stat.exists

- name: Run make for check_rbl # noqa 305
  shell: "make"
  args:
    chdir: "/tmp/check_rbl-{{ icinga2_check_rbl_version }}"
  when: not icinga2_check_rbl_chk.stat.exists

- name: Copy check_rbl to final destination
  copy:
    src: "/tmp/check_rbl-{{ icinga2_check_rbl_version }}/blib/script/check_rbl"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/check_rbl"
    remote_src: yes
    mode: 0755
  when: not icinga2_check_rbl_chk.stat.exists
