---
- set_fact:
    enable_plugins: "{{ enable_plugins | default([]) + [ ansible_role_name ] }}"
  when: >
    ((ansible_facts.all_ipv4_addresses is defined and 
    ansible_facts.all_ipv4_addresses|ansible.netcommon.ipaddr('public')|length>0) and
    icinga2_plugin_autodetect) or
    force_enable_plugin_rbl
