---
- name: Include ido_mysql tasks file.
  include_tasks: ido_mysql.yml

- name: Include api tasks file
  include_tasks: api.yml

- name: Enable Icinga2 features.
  file:
    src: "{{ icinga2_config_dir }}/features-available/{{ item }}.conf"
    path: "{{ icinga2_config_dir }}/features-enabled/{{ item }}.conf"
    owner: "{{ icinga2_user }}"
    group: "{{ icinga2_group }}"
    state: link
    mode: 0755
  loop: "{{ icinga2_enabled_features }}"
