---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if check_docker plugin has been already installed.
  stat:
    path: "{{ icinga2_nagios_plugins_install_dir }}/check_docker"
  register: icinga2_docker_chk

- name: Ensure python3 is installed.
  package:
    name: python3
    state: present
  when: not icinga2_docker_chk.stat.exists

- name: Ensure python3-pip is installed.
  package:
    name: python3-pip
    state: present
  when: not icinga2_docker_chk.stat.exists

- name: Ensure Python docker package is installed.
  pip:
    name: docker
    state: present
  when: not icinga2_docker_chk.stat.exists

- name: Download the docker plugin.
  get_url:
    url: "{{ icinga2_check_docker_download_url }}"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/check_docker"
    mode: 0755
  when: not icinga2_docker_chk.stat.exists

- name: Create initial sudoers file
  file:
    path: /etc/sudoers.d/icinga
    state: touch
    mode: 0600
  when: not icinga2_docker_chk.stat.exists

- name: Set docker sudoers privileges.
  lineinfile:
    line: "{{ item }}"
    path: /etc/sudoers.d/icinga
    validate: /usr/sbin/visudo -cf %s
  loop:
   - "icinga ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_docker"
   - "nagios ALL=(ALL) NOPASSWD: /usr/lib/nagios/plugins/check_docker"
  when: not icinga2_docker_chk.stat.exists
