---
- name: Include distribution dependent variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: Check if plugin has been already installed
  stat:
    path: "{{ icinga2_nagios_plugins_install_dir }}/check_mysql_health"
  register: icinga2_check_mysql_health_chk

- name: Ensure gcc is installed.
  package:
    name: gcc
    state: present
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Download check_mysql_health plugin
  get_url:
    url: "{{ icinga2_check_mysql_health_download_url }}"
    dest: /tmp/
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Unarchive check_mysql_health archive
  unarchive:
    src: "/tmp/{{ icinga2_check_mysql_health_version }}.tar.gz"
    dest: "/tmp/"
    remote_src: yes
    mode: 0755
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Run ./configure for check_mysql_health # noqa 305
  shell: "./configure"
  args:
    chdir: "/tmp/{{ icinga2_check_mysql_health_version }}"
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Run make for check_mysql_health # noqa 305
  shell: "make"
  args:
    chdir: "/tmp/{{ icinga2_check_mysql_health_version }}"
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Run make install for check_mysql_health # noqa 305
  shell: "make install"
  args:
    chdir: "/tmp/{{ icinga2_check_mysql_health_version }}"
  when: not icinga2_check_mysql_health_chk.stat.exists

- name: Copy over compiled check_mysql_health script
  copy:
    src: "/tmp/{{ icinga2_check_mysql_health_version }}/plugins-scripts/check_mysql_health"
    dest: "{{ icinga2_nagios_plugins_install_dir }}/"
    remote_src: yes
    mode: 0755
  when: not icinga2_check_mysql_health_chk.stat.exists
