---
# Icinga2 users and groups. Used in icingaweb and carbon.
icinga2_icingaweb_user: icingaweb2
icinga2_users:
  - name: "{{ icinga2_icingaweb_user }}"
    group: "{{ icinga2_icingaweb_group }}"
  - name: apache
    group: apache
    groups: "apache, {{ icinga2_icingaweb_group }}
