---
- name: Import initial Icinga2 MySQL schema into the icingaweb database.
  mysql_db:
    name: "{{ icinga2_web_mysql_database_name }}"
    state: import
    target: /usr/share/doc/icingaweb2/schema/mysql.schema.sql
    force: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"

- name: Import initial Icinga2 MySQL schema into the IDO database.
  mysql_db:
    name: "{{ icinga2_mysql_database_name }}"
    state: import
    target: /usr/share/icinga2-ido-mysql/schema/mysql.sql
    force: yes
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: "{{ mysql_socket }}"
