---
# Icinga2 config directory.
icinga2_config_dir: /etc/icinga2

# Icinga2 master zone name
icinga2_zone_master_endpoint_name: "master"

icinga2_check_smart_version: 6.8.0
icinga2_check_smart_download_url: https://github.com/Napsty/check_smart/archive/{{ icinga2_check_smart_version }}.tar.gz
